input {
    file {
        path => "/logs/application.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index =>"transaction-service-logs"
    }

    stdout {
        codec => rubydebug
    }
}



